### ISSUE TITLE
images/acm.jpg is not used

### ISSUE THREAD

**Issue by smenon18** [RowanACM/ACM-Website#13]
currently we are not using acm.jpg,

i ran `find . -type f -print | xargs grep "acm.jpg"` and it came back with only .git/index

The image is there but not used anywhere. Is it ok to remove? @RowanACM/web-development

**Comment by RichCerone** [comment]
Can you check where the link is going for the navbar image thumbnail? I thought I made this image the thumbnail on the navbar.

**Comment by smenon18** [comment]
it is images/acm_logo.jpg

**Comment by RichCerone** [comment]
Yeah don't remove that this is being used by the navbar.

**Comment by smenon18** [comment]
acm_logo.jpg is being used by the navbar, i dont see acm.jpg used anywhere

**Comment by RichCerone** [comment]
Ah, I misread it. Yeah I guess remove it I don't know what I was using that for.

**Comment by smenon18** [comment]
commit: 1101dd01f9ee9516a42847aae3497ab978d702d1 removed it in v1
