### ISSUE TITLE
Shaan needs to give me a summary

### ISSUE THREAD

**Issue by RichCerone** [RowanACM/ACM-Website#16]
I added @smenon18 to the treasury position on the website. I need you to give me a summary, because currently it is mine. Also, you need to change the interests section to reflect your own.

**Comment by smenon18** [comment]
i did in Version-1.0.0

commit: 32592432ec5419e966ece81bbf064617543ec64c

**Comment by smenon18** [comment]
@OnThereD needs to upload my picture

**Comment by smenon18** [comment]
@RichCerone You should have synced the Version-1.0.0 branch to master if you were going to create a new one. You made changes I already handled.
