### ISSUE TITLE
Update website on elvis server

### ISSUE THREAD

**Issue by johnsbuck** [RowanACM/ACM-Website#3]
I just need to change the file system so all the old files are together. I know the command and just need to download and move files over.

**Comment by johnsbuck** [comment]
http://elvis.rowan.edu/acm/v1/

**Comment by smenon18** [comment]
Master Updated, need to update elvis server

**Comment by smenon18** [comment]
We are going to connect clone the repository to the elvis server to make this easier

**Comment by smenon18** [comment]
We sucessfully cloned this repo to elvis so now john or rich has to just pull to update it
