### ISSUE TITLE
Board Member page formatting errors

### ISSUE THREAD

**Issue by johnsbuck** [RowanACM/ACM-Website#4]
Board member page has text on on images (div issue). Also Nick Dondiego's bio needs to be reformatted.

![boardmemberissue](https://cloud.githubusercontent.com/assets/5637771/11803887/09b528e4-a2cd-11e5-85ac-d2cfba9b2114.png)

**Comment by smenon18** [comment]
This happens from 990 by X to 1200 by X according to Mozilla's Responsive Design View

**Comment by smenon18** [comment]
Also im going to change the Header above Nick Dondiego from Rowan Animation and Game Development Team to "Comitee Chair's" and then plan to list them all

**Comment by smenon18** [comment]
This bug has to do with image size and what bootsrap considers medium. The image is too large for it to take up only 1/4 of the page. We either need smaller images or to increase the allotted space between the image and the start of the text. I fear that the second option will put too much space between the image and the text for a large screen though. What do you think @onTheRed ?

**Comment by smenon18** [comment]
fixed on v1 branch, commit: de76fa27e7b99aaed57a38e5fc114128da3c35bd
