### ISSUE TITLE
Front page issues

### ISSUE THREAD

**Issue by johnsbuck** [RowanACM/ACM-Website#5]
ACM Calender in elvis.rowan.edu/v1/ is out of frame. Recommend either putting on below Slicebox or other placement.
![boardmemberissue](https://cloud.githubusercontent.com/assets/5637771/11803923/786f232a-a2cd-11e5-8262-58b413f4293c.png)

**Comment by onTheRed** [comment]
The bottom newsfeed is static and doesn't change with the page. I think we just need to remove the static width declarations and replace it with a bootstrap class.

**Comment by johnsbuck** [comment]
When refreshing with the window small, the newsfeed tends to stay in those dimensions, causing issues.
![boardmemberissue](https://cloud.githubusercontent.com/assets/5637771/11804228/44522062-a2d0-11e5-93b1-c34646604f11.png)

Reproducing:
1. Go to elvis.rowan.edu/v1
2. Make your browser window small
3. Hard refresh and expand window.

**Comment by johnsbuck** [comment]
https://feed.mikle.com/support/using-custom-css-with-feedwind-part-1-of-2/

Would recommend removing the script from the main page and instead calling it from the js folder with some custom css.

**Comment by smenon18** [comment]
Calendar now scales responsively, and is in its own row always, still bugs for formating it as the screen gets smaller.

**Comment by smenon18** [comment]
Also since the pictures are different heights, it causes everything else on the front page to jump up and down when they are switched we should have a standardized height or implement a fixed max that it always stays at so this doesnt happen

**Comment by smenon18** [comment]
Calendar and Image Jumping are fixed on v1 all that is left is the rss feed

**Comment by RichCerone** [comment]
I have fixed this issue. The calendar now resizes dynamically.
