### ISSUE TITLE
email.js in two places

### ISSUE THREAD

**Issue by smenon18** [RowanACM/ACM-Website#8]
Curently email.js exist outside a folder and in js/email/ both are made by rich and the correct one should be kept. If it is the one outside a folder it should be moved into the js folder

**Comment by johnsbuck** [comment]
Just as a notice, emailForm.html references the email.js outside of the js folder.

**Comment by smenon18** [comment]
also the one outside looks like a more complete version both were made by @RichCerone so i just wanted to make sure

**Comment by RichCerone** [comment]
I'm pretty sure the one file outside is outside because of an issue routing it to the HTML page.

**Comment by smenon18** [comment]
Is that confirmed it could just be that you tried to use $.post instead of $.ajax because this isnt node.js its a php backend

**Comment by RichCerone** [comment]
Whichever file is linked to that HTML page is the appropriate one.

**Comment by johnsbuck** [comment]
Fixed email.js and emailForm.html in Version-1.0.0 branch. Can be merged whenever.

**Comment by smenon18** [comment]
Are we sure that would work, wouldn't it mess up the ajax url path?

**Comment by johnsbuck** [comment]
Just updated site, so I'll test that now.

**Comment by smenon18** [comment]
Tested and works

**Comment by johnsbuck** [comment]
Confirmed.
